all:
	g++ -o2 -o main.app main.cpp mathplot.cpp connectargsdlg.cpp serialport.cpp enumserial.cpp adaptive_algorithm.cpp FIR.cpp HC_Chen_detect.cpp So_Chen_detect.cpp Pan_Tompkins_detect.cpp FFT.cpp `wx-config --cxxflags --libs` --std=c++11 -m64 -D _MAC_
	./main.app
